### ISSUE TITLE
missing features

### ISSUE THREAD

**Issue by netfun81** [patrickhaller/no-wm#1]
I love the x-alt-tab and x-move-resize programs, however there is no good way to close a program without using xkill or pkill.   The issue with using xkill is that it kills the parent program, for example if you are using xkill to kill a popup browser window it will close the whole browser.  The same with skype or pidgin windows.   Another thing i've noticed is firefox menus wont work without a window manager.  I love the minimalism though, great work!!!

**Comment by patrickhaller** [comment]
See xdotool windowunmap to get rid of pesky windows. 

See http://surf.suckless.org/ to get rid of pesky firefoxes.
