### ISSUE TITLE
Modifying for keyboard based focus?

### ISSUE THREAD

**Issue by robspearman** [patrickhaller/no-wm#2]
This is a great project, but I have a need for keyboard based focus.

At a minimum alt-tab would focus on the last raised window and a new window would get focus upon creation.

I modified x-alt-tab for the first, but am having trouble with x-focus-manager for the second.  I thought I could just use the window from CreateNotify events and give this focus, but that produces a bad window error.  I am not very familiar with Xlib.  Any suggestions?

Also, do you have any interest in incorporating these features once I get it working?

Thanks,

Rob

**Comment by patrickhaller** [comment]
Sure, how did that go?
