### ISSUE TITLE
set border

### ISSUE THREAD

**Issue by ghost** [patrickhaller/no-wm#5]
in no-wm have border but the color is black,whether i can change color border to white? what is file should i change?

**Comment by jsarenik** [comment]
@4L0T there should be no border and the only black color setting is recommended in README and it is related to the color of desktop.

Try to run `pstree` and find the branch with `Xorg` in it. E.g.:

```
$ pstree
...
        ├─login───startx───xinit─┬─Xorg─┬─xf86-video-inte
        │                        │      └─{Xorg}
        │                        └─dwm─┬─battery-mon.sh───sleep
        │                              ├─xautolock
        │                              └─xwrits
...
```

There should not be any wm in your output of `pstree` if you are running in `no-wm` mode.
